import { z } from "zod";

export const SingleStockRequestSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  data: z.object({
    guid: z.string(),
    status: z.string(),
    fromBranch: z.object({
      id: z.number(),
      name: z.string(),
      organizationEmail: z.string(),
    }),
    toBranch: z.object({
      id: z.number(),
      name: z.string(),
      organizationEmail: z.string(),
    }),
    stockRefNumber: z.string(),
    stockData: z.object({
      guid: z.string(),
      createdBy: z.string(),
      updatedBy: z.string(),
      deletedBy: z.string(),
      name: z.string(),
      notes: z.string(),
      status: z.string(),
      category: z.string(),
      quantity: z.string(),
      referenceNumber: z.string(),
      branch: z.string(),
      thresholdQuantity: z.string(),
      deleted: z.boolean(),
      createdAt: z.string(),
      updatedAt: z.string(),
      deletedAt: z.string(),
    }),
    quantity: z.number(),
    createdBy: z.string(),
    updatedBy: z.string(),
    deletedBy: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
    deletedAt: z.string(),
  }),
});
