import { z } from "zod";

export const LoginResponseSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  data: z.object({
    creationChannel: z.string(),
    emailAddress: z.string(),
    username: z.string(),
    mobileNumber: z.string(),
    firstName: z.string(),
    middleName: z.string(),
    lastName: z.string(),
    fullName: z.string(),
    photoLink: z.string(),
    userType: z.string(),
    branch: z.object({
      id: z.number(),
      name: z.string(),
      organizationEmail: z.string(),
    }),
    country: z.object({
      id: z.number(),
      name: z.string(),
      code: z.string(),
    }),
    businessProfile: z.object({
      creationChannel: z.string(),
      companyName: z.string(),
      companyLogo: z.string(),
      emailAddress: z.string(),
      role: z.string(),
      country: z.string(),
      companyState: z.string(),
      companyLga: z.string(),
      companyCity: z.string(),
      street1: z.string(),
      street2: z.string(),
      zip: z.string(),
      phoneNumber: z.string(),
      baseCurrency: z.string(),
      fiscalYear: z.string(),
      startDate: z.string(),
      timeZone: z.string(),
      language: z.string(),
      createdAt: z.string(),
      updatedAt: z.string(),
    }),
    state: z.string(),
    lga: z.string(),
    loginAttempt: z.number(),
    boarded: z.boolean(),
    status: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
    roleName: z.string(),
    credentials: z.object({
      accessToken: z.string(),
      generatedAt: z.string(),
      expiredAt: z.string(),
    }),
  }),
});
