name: Build, Scan, and Deploy Inventory Sandbox Application
on:
  push:
    branches:
      - master
      - staging
      - development
env:
  IMAGE_NAME: "sandbox-inventory-frontend"
  VERSION_TAG: "1.0.0"

jobs:
  build:
    runs-on: self-hosted
    outputs:
      container_name: ${{ steps.set_env.outputs.container_name }}
      port: ${{ steps.set_env.outputs.port }}
      image_tag: ${{ steps.set_env.outputs.image_tag }}
      env_file: ${{ steps.set_env.outputs.env_file }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures full commit history is fetched for accurate scanning

    - name: Set environment variables
      id: set_env
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
          ENV_FILE="/home/ubuntu/envs/frontend/sandbox-prod/prod.env"
          {
            echo "container_name=prod-sandbox-inventory-frontend"
            echo "port=3002:3000"
            echo "image_tag=sandbox-prod-latest"
            echo "env_file=${ENV_FILE}"
          } >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
          ENV_FILE="/home/ubuntu/envs/frontend/sandbox/sandbox-staging.env"
          {
            echo "container_name=staging-sandbox-inventory-frontend"
            echo "port=3003:3000"
            echo "image_tag=sandbox-staging-latest"
            echo "env_file=${ENV_FILE}"
          } >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == 'refs/heads/development' ]]; then
          ENV_FILE="/home/ubuntu/envs/frontend/sandbox/sandbox-development.env"
          {
            echo "container_name=development-sandbox-inventory-frontend"
            echo "port=3004:3000"
            echo "image_tag=sandbox-development-latest"
            echo "env_file=${ENV_FILE}"
          } >> $GITHUB_OUTPUT
        fi
        
    - name: Build Docker Image
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL}" \
          --build-arg NEXT_PUBLIC_CHANNEL_ID="${NEXT_PUBLIC_CHANNEL_ID}" \
          --build-arg NEXT_PUBLIC_CHANNEL_SECRET="${NEXT_PUBLIC_CHANNEL_SECRET}" \
          --build-arg NEXT_PUBLIC_CRYPTO_KEY="${NEXT_PUBLIC_CRYPTO_KEY}" \
          -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
        
        docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:${{ steps.set_env.outputs.image_tag }}

  scan:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Recommended for SonarQube analysis
      
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # SonarQube token
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Example: https://sq.bswlog.co.in/
        
  deploy:
    needs: scan
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        if docker ps -a --format "{{.Names}}" | grep -q "${{ needs.build.outputs.container_name }}"; then
          echo "Container ${{ needs.build.outputs.container_name }} already exists, removing it..."
          docker rm -f "${{ needs.build.outputs.container_name }}"
        fi
        echo "Starting new container: ${{ needs.build.outputs.container_name }}"
        echo "Using env file: ${{ needs.build.outputs.env_file }}"
        
        # Verify env file exists
        if [ ! -f "${{ needs.build.outputs.env_file }}" ]; then
          echo "Error: Environment file ${{ needs.build.outputs.env_file }} not found!"
          exit 1
        fi
        
        docker run -d \
          --name "${{ needs.build.outputs.container_name }}" \
          -p ${{ needs.build.outputs.port }} \
          --env-file "${{ needs.build.outputs.env_file }}" \
          ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}

  cleanup:
    needs: deploy
    runs-on: self-hosted
    steps:
    - name: Cleanup
      run: |
        echo "Cleaning up unused Docker resources..."
        docker system prune -af
        docker image prune -af
