name: Build and Deploy Inventory sandbox application

on:
  push:
    branches:
      - master
      - staging

env:
  IMAGE_NAME: "sandbox-inventory-frontend"
  VERSION_TAG: "1.0.0"

jobs:
  build:
    runs-on: self-hosted
    outputs:
      container_name: ${{ steps.set_env.outputs.container_name }}
      port: ${{ steps.set_env.outputs.port }}
      image_tag: ${{ steps.set_env.outputs.image_tag }}
      env_file: ${{ steps.set_env.outputs.env_file }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      id: set_env
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
          ENV_FILE="/home/ubuntu/envs/frontend/sandbox/sandbox-prod.env"
          {
            echo "container_name=prod-sandbox-inventory-frontend"
            echo "port=3002:3000"
            echo "image_tag=sandbox-prod-latest"
            echo "env_file=${ENV_FILE}"
          } >> $GITHUB_OUTPUT
        else
          ENV_FILE="/home/ubuntu/envs/frontend/sandbox/sandbox-staging.env"
          {
            echo "container_name=staging-sandbox-inventory-frontend"
            echo "port=3003:3000"
            echo "image_tag=sandbox-staging-latest"
            echo "env_file=${ENV_FILE}"
          } >> $GITHUB_OUTPUT
        fi

    - name: Load environment variables
      run: |
        # Export environment variables from file
        set -a
        source "${{ steps.set_env.outputs.env_file }}"
        set +a
        
        # Build with environment variables
        docker build \
          --build-arg NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL}" \
          --build-arg NEXT_PUBLIC_CHANNEL_ID="${NEXT_PUBLIC_CHANNEL_ID}" \
          --build-arg NEXT_PUBLIC_CHANNEL_SECRET="${NEXT_PUBLIC_CHANNEL_SECRET}" \
          -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
        
        docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:${{ steps.set_env.outputs.image_tag }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Deploy
      run: |
        if docker ps -a --format "{{.Names}}" | grep -q "${{ needs.build.outputs.container_name }}"; then
          echo "Container ${{ needs.build.outputs.container_name }} already exists, removing it..."
          docker rm -f "${{ needs.build.outputs.container_name }}"
        fi

        echo "Starting new container: ${{ needs.build.outputs.container_name }}"
        echo "Using env file: ${{ needs.build.outputs.env_file }}"
        
        # Verify env file exists
        if [ ! -f "${{ needs.build.outputs.env_file }}" ]; then
          echo "Error: Environment file ${{ needs.build.outputs.env_file }} not found!"
          exit 1
        fi
        
        # Display env file contents (excluding secrets)
        echo "Environment file contents (excluding secrets):"
        grep -v SECRET "${{ needs.build.outputs.env_file }}" || true
        
        docker run -d \
          --name "${{ needs.build.outputs.container_name }}" \
          -p ${{ needs.build.outputs.port }} \
          --env-file "${{ needs.build.outputs.env_file }}" \
          ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}
        
        # Verify the environment variables
        echo "Verifying environment variables in container:"
        docker exec ${{ needs.build.outputs.container_name }} env | grep NEXT_PUBLIC_

  cleanup:
    needs: deploy
    runs-on: self-hosted
    steps:
    - name: Cleanup
      run: |
        echo "Cleaning up"
        docker system prune -af
        docker image prune -af
